CREATE TABLE ROOMS (ROOM_ID INTEGER PRIMARY KEY , room_type VARCHAR(10), PRICE INTEGER);

CREATE TABLE CUSTOMERS (CUSTOMER_ID INTEGER PRIMARY KEY , FIRST_NAME VARCHAR(10), LAST_NAME VARCHAR(10), EMAIL_ID VARCHAR(100));

CREATE TABLE BOOKINGS (BOOKING_ID INTEGER  PRIMARY KEY, ROOM_ID INTEGER, CUSTOMER_ID INTEGER, FROM_DATE DATE, TO_DATE DATE,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID), FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID));

